### 11
GET http://192.168.1.200/api/v2/usercenter/user/switchUserOrg?deptCode=330800000000J031B000001&sysType=0
content-type: application/json
Authorization: GciBearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MDQ4MjQ2IiwiYXVkIjoid2ViIiwiY3JlYXRlZCI6MTY2MjEyODcyNjA0NCwiYXBwSWQiOm51bGwsImlzcyI6ImljaW5mby5jbiIsImV4cCI6MTY2MjczMzUyNiwiZW1wbG95ZWVDb2RlIjoiR0VfNzFiNzM2NzY0YWM4NDUyNDkwMTdkZTY2MTMzMGUzMGYifQ.2c6k1T8CJXGSPD1rI7KB48p7oSjBymkKIMKgR3gzzWlKl7ssXiD-KHUjc6uMeYkeIyLk5cMuRUgNtsGURBVfxQ

### 
POST http://192.168.1.242:8081/interfaceInfo/getInterfaceInfoById
content-type: application/json

{
    "apiId": "i_f26hh6ai250i0"
}

### 
POST http://192.168.1.242:8081/interfaceInfo/getInterfaceInfoById
content-type: application/json

{
    "apiId": "i_f28a0004e-38n"
}


### 
POST http://192.168.1.242:8081/login
content-type: application/json

{
    "loginType": "local",
    "username":"1",
    "password":"222"
}

### 
GET http://192.168.1.200/api/v2/usercenter/user/readRsa

###

GET http://192.168.1.180:8081/sysDict/internal/list


## coze
### 运行工作流 QPM（每分钟发送的请求数）：60 QPD（每天发送的请求数）：3000
### https://mp.weixin.qq.com/s/4INC33t1LQNtOGQfCQXI9A
POST https://api.coze.cn/v1/workflow/run
content-type: application/json
Authorization: Bearer pat_Q7lrUDdxS03ZOWAbDQiyOBqU4PPW7XOI4qZlniGvGv4SaxTKWnaAV8YUzXDVlSxg

{
    "workflow_id": "7438439100972007439",
    "parameters": {
        "article_url": "https://mp.weixin.qq.com/s/4INC33t1LQNtOGQfCQXI9A"
    }
}


### 获取工作流执行情况 https://api.coze.cn/v1/workflows/{{workflow_id}}/run_histories/{{execute_id}}

GET https://api.coze.cn/v1/workflows/7438439100972007439/run_histories/11
content-type: application/json
Authorization: Bearer pat_Q7lrUDdxS03ZOWAbDQiyOBqU4PPW7XOI4qZlniGvGv4SaxTKWnaAV8YUzXDVlSxg
