import { mock } from 'mockjs'
export default [
    {
        name: '/punish/stagedoc/common/getDocBaseInfo',
        method: 'post',
        description: '文书模板',
        onMock(opt, query, body) {
            return mock({
                code: 200,
                message: '获取成功',
                data: {
                    htmlContent:
                        '<div style=" width: 650px;background-color: white;margin: auto;font-family:FangSong; font-size:18px;word-break:break-all;word-wrap:break-word;">\t<p style="font-size:22pt; line-height:91%; margin:12.65pt 0pt 0pt; orphans:0; text-align:center; widows:0">\t\t<span style="font-family:SimHei; font-size:22pt; letter-spacing:-0.05pt">\t\t\t<span style="word-break:break-all;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="orgStandardName"> </span>\t\t\t<span class="edit-able configured" data-key="orgStandardName"></span>\t\t</span>\t</p>\t<p style="font-size:22pt; line-height:91%; margin:12.65pt 0pt 0pt; orphans:0; text-align:center; widows:0">\t\t<span style="font-family:SimHei; font-size:22pt; letter-spacing:-0.05pt">轻微违法告知承诺书</span>\t</p>\t<p style="font-size:12pt; line-height:77%; margin:13.45pt 0pt 0pt; orphans:0; text-align:right; widows:0">\t\t<span style="font-family:FangSong; font-size:12pt; letter-spacing:-0.55pt">\t\t\t<span style="word-break:break-all;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="documentNumber"> </span>\t\t\t<span class="edit-able configured" data-key="documentNumber"></span>\t\t</span>\t</p>\t<p style="line-height:4.2pt; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t<span style="font-family:Calibri; font-size:10.5pt">&nbsp;  </span>\t</p>\t<table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin-left:0.12pt; width:449.65pt">\t\t<tbody>\t\t\t<tr style="height:48.65pt">\t\t\t\t<td rowspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:31.25pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:121%; margin:3.45pt 5.45pt 0pt 5.85pt; orphans:0; text-align:justify; text-indent:1.2pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.95pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:121%; margin:3.45pt 5.45pt 0pt 5.85pt; orphans:0; text-align:justify; text-indent:1.2pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.95pt">当事</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.05pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.35pt">人的</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.05pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.35pt">情况</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:52.9pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:121%; margin:8.95pt 5.55pt 0pt 5.8pt; orphans:0; padding-left:12pt; text-align:justify; text-indent:-12pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">姓名/名</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.1pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">称</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:128.9pt">\t\t\t\t\t<p style="text-align:center; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong;text-align:center;  font-size:10.5pt">\t\t\t\t\t\t\t<span style="word-break:break-all;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="partyName"> </span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="partyName"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:70.6pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:121%; margin:8.95pt 5.45pt 0pt 6.55pt; orphans:0; padding-left:6.15pt; text-align:justify; text-indent:-6.15pt; ">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.1pt">证件号/</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.05pt">信用代码</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:161.5pt">\t\t\t\t\t<p style=" text-align:center; ">\t\t\t\t\t\t<span style="font-family:FangSong; text-align:center; font-size:10.5pt">\t\t\t\t\t\t\t<span style="word-break:break-all;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="zjhm"> </span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="zjhm"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t</tr>\t\t\t<tr style="height:48.45pt">\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:52.9pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:128%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:3.4pt 0pt 0pt; orphans:0; text-align:justify; text-indent:12.35pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">地址</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; text-align:center;border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:128.9pt">\t\t\t\t\t<p style=" text-align:center;">\t\t\t\t\t\t<span style="font-family:FangSong; text-align:center;  font-size:10.5pt">\t\t\t\t\t\t\t<span style="word-break:break-all;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="partiesAddress"> </span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="partiesAddress"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:70.6pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:128%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:3.4pt 0pt 0pt; orphans:0; text-align:justify; text-indent:13.1pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">联系电话</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:161.5pt">\t\t\t\t\t<p style=" text-align:center;">\t\t\t\t\t\t<span style="font-family:FangSong; text-align:center; font-size:10.5pt；">\t\t\t\t\t\t\t<span style="word-break:break-all;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="phone"> </span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="phone"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t</tr>\t\t\t<tr style="height:184.4pt">\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:31.25pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:111%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:111%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:111%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:111%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:111%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:121%; margin:3.4pt 5.45pt 0pt 5.8pt; orphans:0; text-align:justify; text-indent:0.1pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.35pt">违法</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.05pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.3pt">行为</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.05pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.3pt">告知</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:416.15pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:146%; margin:7.05pt 0pt 0pt; text-align:justify; text-indent:26.15pt">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">\t\t\t\t\t\t\t<span class="insert-elem datehourminute-control" app-type="3" data-key="checkTime"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="checkTime"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.8pt">，执法人员</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">\t\t\t\t\t\t\t<span style="border-bottom: 1px solid #000;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="zfrymz"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="zfrymz"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">在</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">\t\t\t\t\t\t\t<span style="border-bottom: 1px solid #000;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="afdd"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="afdd"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">实施检查时，发现当事人存在违法行为，根据</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">\t\t\t\t\t\t\t<span style="border-bottom: 1px solid #000;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="law"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="law"></span>\t\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">的规定，现责令当事人于</span>\t\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">\t\t\t\t\t\t\t\t<span class="insert-elem datetime-control" app-type="3" data-key="dutyRectifyTime"></span>\t\t\t\t\t\t\t\t<span class="edit-able configured curr-edit" data-key="dutyRectifyTime"></span>\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">前整改完毕。</span>\t\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-3.05pt"> </span>\t\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">改正要求如</span>\t\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.85pt">下：</span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:146%; margin:7.05pt 0pt 0pt; text-align:justify; text-indent:21pt">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt">\t\t\t\t\t\t\t<span style="border-bottom: 1px solid #000;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="gzyq"> </span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="gzyq"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:146%; margin:7.05pt 0pt 0pt; text-align:justify; text-indent:26.15pt">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">经查，该案件违法情节轻微，符合轻微违法告知承诺制的适用条件。执法人员已向当</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">事人宣传了相关法律法规规章的规定。</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:6.7pt 0pt 0pt; orphans:0; text-align:justify; text-indent:194.85pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="margin:6.7pt 0pt 0pt;orphans:0; text-align:justify; text-indent:10.5pt;widows:0">\t\t\t\t\t\t<span style="font-family:FangSong;font-size:10.5pt;">执法人员签名：</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">\t\t\t\t\t\t\t<span class="insert-elem" app-type="12" data-key="mainHandleSignPic">\t\t\t\t\t\t\t\t<img style="width: 150px;height: 60px;">\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="mainHandleSignPic"></span>\t\t\t\t\t\t\t<span class="insert-elem" app-type="12" data-key="assistHandleSignPic">\t\t\t\t\t\t\t\t<img style="width: 150px;height: 60px;">\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="assistHandleSignPic"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:7.55pt 0pt 0pt; orphans:0; text-align:justify; text-indent:289.15pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">&nbsp;  </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">\t\t\t\t\t\t\t<span class="insert-elem sign" style="color:#fff; font-size:6pt;" app-type="4">签章处</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="sealLocation"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:7.55pt 0pt 0pt; orphans:0; text-align:justify; text-indent:289.15pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.55pt">\t\t\t\t\t\t\t<span class="insert-elem date-control" app-type="3" data-key="sealDate"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="sealDate"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t</tr>\t\t\t<tr style="height:33.05pt">\t\t\t\t<td style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:31.25pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:108%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:108%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:108%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:108%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:108%; margin:0pt; orphans:0; text-align:justify; widows:0">\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt">&nbsp;  </span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:121%; margin:3.4pt 5.45pt 0pt 5.85pt; orphans:0; text-align:justify; text-indent:1.2pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.95pt">当事</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.05pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.35pt">人的</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:0.05pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.35pt">承诺</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td colspan="4" style="border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:416.15pt">\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:5.65pt 0pt 0pt; orphans:0; text-align:justify; text-indent:6.8pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">\t\t\t\t\t\t\t<span style="border-bottom: 1px solid #000;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="orgStandardName1"> </span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="orgStandardName1"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">：</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:132%; margin:7.65pt 5.45pt 0pt 5.15pt; orphans:0; text-align:justify; text-indent:21.65pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">执法人员已向本人（单位）</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">进行了相关告知和法律宣传教育，并要求予以改正。本人</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">（单位）</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.3pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt">对以上情况确认无误，并自愿承诺：</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:84%; margin:0pt; orphans:0; text-align:justify; text-indent:27.8pt; widows:0">\t\t\t\t\t\t<span style="color:#666666; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">\t\t\t\t\t\t\t<span class="insert-elem" app-type="8" readonly="true" data-key="xx1">\t\t\t\t\t\t\t\t<input type="checkbox">1.</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="xx1"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">立即予以改正；</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:6.45pt 0pt 0pt; orphans:0; text-align:justify; text-indent:27.8pt; widows:0">\t\t\t\t\t\t<span style="color:#666666; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">\t\t\t\t\t\t\t<span class="insert-elem" app-type="8" readonly="true" data-key="xx2">\t\t\t\t\t\t\t\t<input type="checkbox">2.</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="xx2"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">\t\t\t\t\t\t\t<span class="insert-elem datehourminute-control" app-type="3" data-key="gzwbrq"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="gzwbrq"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">前整改完毕，并将整改情况说明等材料送达你单位；</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:7.55pt 0pt 0pt; orphans:0; text-align:justify; text-indent:27.8pt; widows:0">\t\t\t\t\t\t<span style="color:#666666; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.1pt">\t\t\t\t\t\t\t<span class="insert-elem" app-type="8" readonly="true" data-key="xx3">\t\t\t\t\t\t\t\t<input type="checkbox">3.</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="xx3"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:\'Times New Roman\'; font-size:10.5pt; letter-spacing:-0.1pt">.</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.1pt">今后将严格遵守相关法律法规规章的规定。</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:7.55pt 0pt 0pt; orphans:0; text-align:justify; text-indent:26.65pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">若本人（单位）</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.25pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.2pt">未履行上述承诺的，愿依法承担相应法律责任。</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="margin:7.55pt 0pt 0pt; orphans:0; text-align:justify; text-indent:215.35pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">签名或盖章：</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt"> </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">&nbsp;  </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">\t\t\t\t\t\t\t<span class="insert-elem" app-type="12" data-key="signFingerprintPic">\t\t\t\t\t\t\t\t<img style="width: 100px;height: 60px;">\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="signFingerprintPic"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:7.55pt 0pt 0pt; orphans:0; text-align:justify; text-indent:320.35pt; widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.55pt">\t\t\t\t\t\t\t<span class="insert-elem date-control" app-type="3" data-key="signFingerprintDate"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="signFingerprintDate"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t</tr>\t\t\t<tr style="height:49.95pt">\t\t\t\t<td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; height:49.95pt; vertical-align:top; width:31.25pt; writing-mode:tb-rl">\t\t\t\t\t<p style="font-size:10.5pt;/* line-height:75%; */margin:10.6pt -2pt 0pt;orphans:0;text-align: center;text-indent:11.55pt;widows:0">\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.1pt">备注</span>\t\t\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t\t<td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:0.75pt; border-left-color:#000000; border-left-style:solid; border-left-width:0.75pt; border-right-color:#000000; border-right-style:solid; border-right-width:0.75pt; border-top-color:#000000; border-top-style:solid; border-top-width:0.75pt; vertical-align:top; width:416.15pt">\t\t\t\t\t<span style="border-bottom: 1px solid #000;" class="insert-elem" placeholder="请输入内容" contenteditable="false" app-type="1" data-key="bz"> </span>\t\t\t\t\t<span class="edit-able configured" data-key="bz"></span>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:3.25pt 0pt 0pt; orphans:0; text-align:justify; text-indent:5.15pt; widows:0">\t\t\t\t\t\t<span style="color:#ffffff; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.05pt">（注明当事人</span>\t\t\t\t\t\t<span style="color:#ffffff; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.05pt"></span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">执法人员签名：<span class="insert-elem" app-type="12" data-key="mainHandleSignPic1">\t\t\t\t\t\t\t\t<img style="width: 150px;height: 60px;">\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="mainHandleSignPic1"></span>\t\t\t\t\t\t</span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.15pt">\t\t\t\t\t\t\t<span class="insert-elem" app-type="12" data-key="assistHandleSignPic1">\t\t\t\t\t\t\t\t<img style="width: 150px;height: 60px;">\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="assistHandleSignPic1"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t\t<p style="font-size:10.5pt; line-height:76%; margin:3.25pt 0pt 0pt; orphans:0; text-align:justify; text-indent:252pt; widows:0">\t\t\t\t\t\t<span style="color:#ffffff; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.05pt">名</span>\t\t\t\t\t\t<span style="color:#ffffff; font-family:FangSong; font-size:10.5pt; letter-spacing:-0.05pt">&nbsp;  </span>\t\t\t\t\t\t<span style="font-family:FangSong; font-size:10.5pt; letter-spacing:-0.55pt">\t\t\t\t\t\t\t<span class="insert-elem date-control" app-type="3" data-key="zfryqmsj"></span>\t\t\t\t\t\t\t<span class="edit-able configured" data-key="zfryqmsj"></span>\t\t\t\t\t\t</span>\t\t\t\t\t</p>\t\t\t\t</td>\t\t\t</tr>\t\t\t<tr style="height:0pt">\t\t\t\t<td style="width:32pt; border:none"></td>\t\t\t\t<td style="width:53.65pt; border:none"></td>\t\t\t\t<td style="width:129.65pt; border:none"></td>\t\t\t\t<td style="width:71.35pt; border:none"></td>\t\t\t\t<td style="width:162.25pt; border:none"></td>\t\t\t</tr>\t\t</tbody>\t</table></div>',
                    templateCode: null,
                    templateName: null,
                    templateConfigMap: {
                        assistHandleSignPic1: {
                            controlConfigContent: '{"width":"150px","height":"60px"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '协办人签名',
                            isRequired: '',
                            isAutoData: '0',
                            templateFieldEn: 'assistHandleSignPic1',
                            controlType: '12',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '25',
                            isShowLabel: '1',
                            controlGroupId: '3c2241df-8e76-487c-d566-bb5f6336ad51',
                        },
                        partiesPersonInfoForPdfList: {
                            controlConfigContent: '{}',
                            isShowOnPhone: '1',
                            templateFieldCn: '当事人循环体',
                            isRequired: '',
                            isAutoData: '0',
                            templateFieldEn: 'partiesPersonInfoForPdfList',
                            controlType: '14',
                            isUnderline: '0',
                            controlSort: '28',
                            isShowLabel: '1',
                            controlGroupId: '3cd3d4f4-1f1b-4825-8fb4-b81610c224de',
                        },
                        documentNumber: {
                            controlConfigContent: '{"placeholder":"","maxLen":"50","defaultDisplayLen":"1","inputType":"single","isEdit":0}',
                            isShowOnPhone: '0',
                            templateFieldCn: '文书文号',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'documentNumber',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '3',
                            isShowLabel: '0',
                            controlGroupId: '2a6439b2-6c83-4c91-d621-9025d063400f',
                        },
                        afdd: {
                            controlConfigContent: '{"placeholder":"","maxLen":"200","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            dataGenerateRule: '${case_main_detail_info.case_happen_address_detail}',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: 'SOURCE_SYSTEM',
                            isShowOnPhone: '1',
                            templateFieldCn: '案发地点',
                            isAutoData: '1',
                            templateFieldEn: 'afdd',
                            controlType: '1',
                            linkageRule: '',
                            controlSort: '9',
                            isShowLabel: '1',
                            controlGroupId: '10bfd2fd-7076-4aa9-8bba-e7be40a0136e',
                        },
                        gzwbrq: {
                            controlConfigContent: '{"isEdit":1,"pickerType":"datehourminute","timeShow":"yyyy年MM月dd日 HH时mm分ss秒"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '改正完毕日期',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'gzwbrq',
                            controlType: '3',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '20',
                            isShowLabel: '1',
                            controlGroupId: '1ab6b0d7-c2f6-4f36-f78d-be8e8c7e40aa',
                        },
                        mainHandleSignPic1: {
                            controlConfigContent: '{"width":"150px","height":"60px"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '主办人签名',
                            isRequired: '',
                            isAutoData: '0',
                            templateFieldEn: 'mainHandleSignPic1',
                            controlType: '12',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '24',
                            isShowLabel: '1',
                            controlGroupId: '6d30bd81-efc4-4e93-c4cb-14f3329993e7',
                        },
                        zjhm: {
                            controlConfigContent: '{"placeholder":"","maxLen":"50","defaultDisplayLen":"1","inputType":"single","isEdit":0}',
                            isShowOnPhone: '1',
                            templateFieldCn: '证件号码',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'zjhm',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '4',
                            isShowLabel: '1',
                            controlGroupId: '2e79e9a8-313c-46f6-fcdc-39fa65eb215e',
                        },
                        partiesAddress: {
                            controlConfigContent: '{"placeholder":"","maxLen":"200","defaultDisplayLen":"1","inputType":"single","isEdit":0}',
                            isShowOnPhone: '1',
                            templateFieldCn: '住址',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'partiesAddress',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '5',
                            isShowLabel: '1',
                            controlGroupId: '0da9e6ab-b1a5-4ec0-adaf-4bc9d1b745e0',
                        },
                        assistHandleSignPic: {
                            controlConfigContent: '{"width":"150px","height":"60px"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '协办人签名',
                            isRequired: '',
                            isAutoData: '0',
                            templateFieldEn: 'assistHandleSignPic',
                            controlType: '12',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '13',
                            isShowLabel: '1',
                            controlGroupId: 'd988e6ba-3ab0-4f85-cacc-7fef99690b57',
                        },
                        zfryqmsj: {
                            controlConfigContent: '{"isEdit":1,"pickerType":"date","timeShow":"yyyy年MM月dd日 HH时mm分ss秒"}',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: 'DATETIME_FILL_DAY',
                            isShowOnPhone: '1',
                            templateFieldCn: '执法人员签名时间',
                            isAutoData: '1',
                            templateFieldEn: 'zfryqmsj',
                            controlType: '3',
                            linkageRule: '',
                            controlSort: '21',
                            isShowLabel: '1',
                            controlGroupId: '6d240a61-9ba8-467f-fc28-42f2797bd22a',
                        },
                        orgStandardName1: {
                            controlConfigContent: '{"placeholder":"","maxLen":"20","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            dataGenerateRule: '${sys_depart_param.org_standard_name}',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: 'SOURCE_SYSTEM',
                            isShowOnPhone: '1',
                            templateFieldCn: '标准文书抬头',
                            isAutoData: '1',
                            templateFieldEn: 'orgStandardName1',
                            controlType: '1',
                            linkageRule: '',
                            controlSort: '16',
                            isShowLabel: '1',
                            controlGroupId: 'dbcc2823-2562-4ceb-b158-2dc10d0176fd',
                        },
                        bz: {
                            controlConfigContent: '{"placeholder":"","maxLen":"200","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            isShowOnPhone: '1',
                            templateFieldCn: '备注',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'bz',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '23',
                            isShowLabel: '1',
                            controlGroupId: '045809d0-5e7b-45de-c5af-90bccf319c4e',
                        },
                        partyName: {
                            controlConfigContent: '{"placeholder":"","maxLen":"50","defaultDisplayLen":"1","inputType":"single","isEdit":0}',
                            isShowOnPhone: '1',
                            templateFieldCn: '当事人',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'partyName',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '1',
                            isShowLabel: '1',
                            controlGroupId: 'c2427e9f-1b6d-46cd-c825-82fde43104be',
                        },
                        orgStandardName: {
                            controlConfigContent: '{"placeholder":"","maxLen":"100","defaultDisplayLen":"1","inputType":"single","isEdit":0}',
                            dataGenerateRule: '${sys_depart_param.org_standard_name}',
                            isRequired: '0',
                            isUnderline: '0',
                            autoDataSource: 'SOURCE_SYSTEM',
                            isShowOnPhone: '0',
                            templateFieldCn: '标准文书抬头',
                            isAutoData: '1',
                            templateFieldEn: 'orgStandardName',
                            controlType: '1',
                            linkageRule: '',
                            controlSort: '26',
                            isShowLabel: '0',
                            controlGroupId: '49e7ea6a-083e-45b3-c38a-c15ca5157527',
                        },
                        wfss: {
                            controlConfigContent: '{"placeholder":"","maxLen":"500","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            dataGenerateRule: '${case_main_detail_info.illegal_fact}',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: 'SOURCE_SYSTEM',
                            isShowOnPhone: '1',
                            templateFieldCn: '违法事实',
                            isAutoData: '1',
                            templateFieldEn: 'wfss',
                            controlType: '1',
                            linkageRule: '',
                            controlSort: '10',
                            isShowLabel: '1',
                            controlGroupId: '8eb3c95e-f659-48e1-baa5-9db195599c32',
                        },
                        signFingerprintDate: {
                            controlConfigContent: '{"isEdit":1,"pickerType":"date","timeShow":"yyyy年MM月dd日 HH时mm分ss秒"}',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: 'DATETIME_FILL_DAY',
                            isShowOnPhone: '1',
                            templateFieldCn: '承诺签字时间',
                            isAutoData: '1',
                            templateFieldEn: 'signFingerprintDate',
                            controlType: '3',
                            linkageRule: '',
                            controlSort: '22',
                            isShowLabel: '1',
                            controlGroupId: '9b97f3e2-c01c-41fc-bc99-4b4565621d3d',
                        },
                        sealDate: {
                            controlConfigContent: '{"isEdit":1,"pickerType":"date","timeShow":"yyyy年MM月dd日 HH时mm分ss秒"}',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: 'DATETIME_FILL_DAY',
                            isShowOnPhone: '1',
                            templateFieldCn: '盖章日期',
                            isAutoData: '1',
                            templateFieldEn: 'sealDate',
                            controlType: '3',
                            linkageRule: '',
                            controlSort: '15',
                            isShowLabel: '1',
                            controlGroupId: '69c57fd3-5887-4211-d58f-6434f2c7a8f7',
                        },
                        zfrymz: {
                            controlConfigContent: '{"placeholder":"","maxLen":"100","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            isShowOnPhone: '1',
                            templateFieldCn: '执法人员名字',
                            isRequired: '1',
                            isAutoData: '0',
                            templateFieldEn: 'zfrymz',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '8',
                            isShowLabel: '1',
                            controlGroupId: 'd324e8b6-a5a4-4576-cd52-9261a6dc87d6',
                        },
                        law: {
                            controlConfigContent: '{"placeholder":"","maxLen":"200","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            isShowOnPhone: '1',
                            templateFieldCn: '法律法规',
                            isRequired: '1',
                            isAutoData: '0',
                            templateFieldEn: 'law',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '29',
                            isShowLabel: '0',
                            controlGroupId: '455cf518-4551-43f7-e385-c93c546fb7f3',
                        },
                        mainHandleSignPic: {
                            controlConfigContent: '{"width":"150px","height":"60px"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '主办人签名',
                            isRequired: '',
                            isAutoData: '0',
                            templateFieldEn: 'mainHandleSignPic',
                            controlType: '12',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '12',
                            isShowLabel: '1',
                            controlGroupId: '719e1efb-d2fe-4e35-f738-ae58d60d880c',
                        },
                        xx1: {
                            controlConfigContent: '{"textVal":"1."}',
                            dataGenerateRule: '',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: '',
                            isShowOnPhone: '1',
                            templateFieldCn: '选项1',
                            isAutoData: '',
                            templateFieldEn: 'xx1',
                            controlType: '8',
                            linkageRule: '',
                            controlSort: '17',
                            isShowLabel: '1',
                            controlGroupId: '5fe42bf5-0fa3-474d-ab4e-e6cbd0033c8e',
                        },
                        xx3: {
                            controlConfigContent: '{"textVal":"3."}',
                            dataGenerateRule: '',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: '',
                            isShowOnPhone: '1',
                            templateFieldCn: '选项3',
                            isAutoData: '',
                            templateFieldEn: 'xx3',
                            controlType: '8',
                            linkageRule: '',
                            controlSort: '19',
                            isShowLabel: '1',
                            controlGroupId: '331908e4-6722-4236-b269-009f8878d743',
                        },
                        xx2: {
                            controlConfigContent: '{"textVal":"2."}',
                            dataGenerateRule: '',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: '',
                            isShowOnPhone: '1',
                            templateFieldCn: '选项2',
                            isAutoData: '',
                            templateFieldEn: 'xx2',
                            controlType: '8',
                            linkageRule: '',
                            controlSort: '18',
                            isShowLabel: '1',
                            controlGroupId: 'b6ba882e-9169-493d-8b8c-18f6bb5a9ae6',
                        },
                        checkTime: {
                            controlConfigContent: '{"isEdit":1,"pickerType":"datehourminute","timeShow":"yyyy年MM月dd日 HH时mm分ss秒"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '检查时间',
                            isRequired: '1',
                            isAutoData: '0',
                            templateFieldEn: 'checkTime',
                            controlType: '3',
                            isUnderline: '0',
                            linkageRule:
                                "{\r\n  watch: ['checkTime'],\r\n  handler(obj) {\r\n    let http = obj.http\r\n    let checkTime = obj.values.checkTime || ''\r\n    if(checkTime==null || checkTime==''){\r\n      return {value: ''}\r\n    }\r\n    if(checkTime.indexOf('日')>0){\r\n       checkTime =checkTime.substring(0,checkTime.indexOf('日'))\r\n       checkTime=checkTime.replace('年','/').replace('月','/')\r\n    }\r\n\t  let today = new Date()\r\n    \r\n   let todayStamp = new Date(new Date(new Date().toLocaleDateString()).getTime()).getTime()   // 当天零点\r\n    let selectStamp = new Date(Date.parse(checkTime.replace(/-/g, \"/\"))).getTime()\r\n    if(todayStamp < selectStamp ){\r\n      alert('听证提出时间只能选择今日及之前的日期')\r\n      return {value: ''}\r\n    }\r\n     return {value: obj.values.checkTime || ''}\r\n  },\r\n}",
                            controlSort: '7',
                            isShowLabel: '1',
                            controlGroupId: 'fdd669d6-077c-4f23-98f7-c0c368a0c705',
                        },
                        phone: {
                            controlConfigContent: '{"placeholder":"","maxLen":"20","defaultDisplayLen":"1","inputType":"single","isEdit":0}',
                            isShowOnPhone: '1',
                            templateFieldCn: '电话',
                            isRequired: '0',
                            isAutoData: '0',
                            templateFieldEn: 'phone',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '6',
                            isShowLabel: '1',
                            controlGroupId: '48e79bcd-21bf-4eb7-bc4d-31001250adc3',
                        },
                        signFingerprintPic: {
                            controlConfigContent: '{"width":"100px","height":"60px"}',
                            isRequired: '',
                            isUnderline: '0',
                            isShowOnPhone: '1',
                            templateFieldCn: '当事人签字',
                            isAutoData: '0',
                            templateFieldEn: 'signFingerprintPic',
                            controlType: '12',
                            linkageRule: '',
                            controlSort: '21',
                            isShowLabel: '1',
                            signatureKeyword: '签章处',
                            controlGroupId: '1db7f878-e8a6-4bf6-e5d5-9749c2786f09',
                        },
                        sealLocation: {
                            controlConfigContent: '{}',
                            dataGenerateRule: '',
                            isRequired: '1',
                            isUnderline: '0',
                            autoDataSource: '',
                            isShowOnPhone: '1',
                            templateFieldCn: 'sealLocation',
                            isAutoData: '',
                            templateFieldEn: 'sealLocation',
                            controlType: '4',
                            linkageRule: '',
                            controlSort: '14',
                            isShowLabel: '1',
                            signatureKeyword: '签章处',
                            controlGroupId: 'e28de7b6-8a2a-41ba-bdca-ad64b4defdec',
                        },
                        gzyq: {
                            controlConfigContent: '{"placeholder":"","maxLen":"500","defaultDisplayLen":"1","inputType":"single","isEdit":1}',
                            isShowOnPhone: '1',
                            templateFieldCn: '改正要求',
                            isRequired: '1',
                            isAutoData: '0',
                            templateFieldEn: 'gzyq',
                            controlType: '1',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '22',
                            isShowLabel: '1',
                            controlGroupId: 'c8381232-b5ea-4248-fda8-22b0ff5897c1',
                        },
                        dutyRectifyTime: {
                            controlConfigContent: '{"isEdit":1,"pickerType":"datehourminute","timeShow":"yyyy年MM月dd日 HH时mm分ss秒"}',
                            isShowOnPhone: '1',
                            templateFieldCn: '责令改正时间',
                            isRequired: '1',
                            isAutoData: '0',
                            templateFieldEn: 'dutyRectifyTime',
                            controlType: '3',
                            isUnderline: '0',
                            linkageRule: '',
                            controlSort: '27',
                            isShowLabel: '1',
                            controlGroupId: '5a5aaf52-9c53-47d2-9e59-1268bc259c78',
                        },
                    },
                },
            })
        },
    },
    {
        name: '/punish/stagedoc/common/saveDocInfo',
        method: 'post',
        description: '文书保存',
        onMock(opt, query, body) {
            return mock({
                code: 200,
                message: '请求成功',
            })
        },
    },
    {
        name: '/punish/stagedoc/common/getDocFormData',
        method: 'post',
        description: '文书表单数据',
        onMock(opt, query, body) {
            return mock({
                code: 200,
                message: '获取成功',
                data: {
                    operateType: '1',
                    dataMap: {
                        zfrymz: '11',
                        law: '22',
                        gzyq: '33',
                        zfryqmsj: '测试',
                        orgStandardName1: '啧啧啧啧啧啧',
                        afdd: '测试',
                        orgStandardName: '测试',
                        wfss: '测试',
                        signFingerprintDate: '2025-01-15 10:00:00',
                        sealDate: '2025-01-15 10:00:00',
                        checkTime: '2025年01月16日15时08分',
                        dutyRectifyTime: '2025年01月16日15时08分',
                    },
                    templateCode: 'DT2A0223300QWWFGJCNS0000000001',
                },
            })
        },
    },
]
