// 获取考卷列表数据
export const list = async (params?: any) => {
    return {
        code: 200,
        message: 'success',
        data: {
            data: [
                {
                    id: '48',
                    title: '2024年全省协助执法文员考试试卷',
                    duration: '60',
                    is_del: '0',
                    del_time: null,
                    grade_z: '170',
                    kind: '6',
                    grade_score: '100',
                    dan_grade: '0.5',
                    duo_grade: '1',
                    pan_grade: '0.5',
                    case_grade: '2',
                    className: null,
                    case: 0,
                    dan: 110,
                    duo: 30,
                    pan: 30,
                },
                {
                    id: '47',
                    title: '2024年党纪法规知识考试',
                    duration: '45',
                    grade_z: '90',
                    grade_score: '100',
                    dan_grade: '1',
                    duo_grade: '2',
                    pan_grade: '1',
                    case_grade: '5',
                    case: 0,
                    dan: 50,
                    duo: 30,
                    pan: 10,
                },
                {
                    id: '46',
                    title: '2024年政工岗位练兵考试',
                    duration: '60',
                    grade_z: '90',
                    grade_score: '100',
                    dan_grade: '1',
                    duo_grade: '2',
                    pan_grade: '1',
                    case_grade: '5',
                    case: 2,
                    dan: 40,
                    duo: 20,
                    pan: 20,
                },
                {
                    id: '45',
                    title: '2024年基层党务工作者考试',
                    duration: '60',
                    grade_z: '90',
                    grade_score: '100',
                    dan_grade: '1',
                    duo_grade: '2',
                    pan_grade: '1',
                    case_grade: '5',
                    case: 2,
                    dan: 40,
                    duo: 20,
                    pan: 20,
                },
                {
                    id: '44',
                    title: '2024年机关党建知识考试',
                    duration: '45',
                    grade_z: '80',
                    grade_score: '100',
                    dan_grade: '1',
                    duo_grade: '2',
                    pan_grade: '1',
                    case_grade: '5',
                    case: 0,
                    dan: 40,
                    duo: 20,
                    pan: 20,
                },
            ],
            recordsTotal: 5,
        },
    }
}
