import { ExAxiosRequestConfig } from 'icinfo-request'
import { http } from '@/scripts/http'

/**
 * 获取我的卷宗列表
 */
export const list = async (params?: any) => {
    return {
        code: 200,
        message: 'success',
        data: {
            data: [
                {
                    id: 1,
                    caseType: '行政处罚',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX等2个',
                    returnDate: '2022-10-11',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '1',
                    updateTime: '2022-10-11 12:00:00',
                },
                {
                    id: 2,
                    caseType: '行政检查',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX',
                    returnDate: '2022-10-10',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '2',
                    updateTime: '2022-10-10 12:00:00',
                },
                {
                    id: 3,
                    caseType: '行政处罚',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX等3个',
                    returnDate: '2022-10-09',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '3',
                    rejectReason: '材料不完整，请补充相关证明文件',
                    updateTime: '2022-10-09 12:00:00',
                },
                {
                    id: 4,
                    caseType: '行政检查',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX',
                    returnDate: '2022-10-08',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '1',
                    updateTime: '2022-10-08 12:00:00',
                },
                {
                    id: 5,
                    caseType: '行政处罚',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX等2个',
                    returnDate: '2022-10-07',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '2',
                    updateTime: '2022-10-07 12:00:00',
                },
                {
                    id: 6,
                    caseType: '行政检查',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX',
                    returnDate: '2022-10-06',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '3',
                    rejectReason: '请补充现场检查记录',
                    updateTime: '2022-10-06 12:00:00',
                },
                {
                    id: 7,
                    caseType: '行政处罚',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX等4个',
                    returnDate: '2022-10-05',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '1',
                    updateTime: '2022-10-05 12:00:00',
                },
                {
                    id: 8,
                    caseType: '行政检查',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX',
                    returnDate: '2022-10-04',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '2',
                    updateTime: '2022-10-04 12:00:00',
                },
                {
                    id: 9,
                    caseType: '行政处罚',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX等2个',
                    returnDate: '2022-10-03',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '3',
                    rejectReason: '请完善处罚依据说明',
                    updateTime: '2022-10-03 12:00:00',
                },
                {
                    id: 10,
                    caseType: '行政检查',
                    caseName: 'XXXXX立字〔2022〕第XXXXXX号',
                    target: 'XXX',
                    returnDate: '2022-10-02',
                    returnNo: 'XXXXX立字〔2022〕第XXXXXX号',
                    status: '1',
                    updateTime: '2022-10-02 12:00:00',
                },
            ],
            recordsTotal: 10,
        },
    }
}
